class JobsList{
  static List jobList = [
    {
      "image" : "https://img.freepik.com/free-icon/search_318-265146.jpg",
      "title" : "Senior Software Developer",
      "details" : "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia, molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum numquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium optio, eaque rerum! Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut! Impedit sit sunt quaerat, odit, tenetur error, harum nesciunt ipsum debitis quas aliquid. Reprehenderit, quia. Quo neque error repudiandae fuga? Ipsa laudantium molestias eos sapiente officiis modi at sunt excepturi.",
      "salary" : "\$1,00,0000/yr",
      "company" : "Google",
      "type" : "Full–time",
      "location" : "Anywhere in India",
      "vacancy" : "3",
      "edu" : "Bachelor's degree in supply chain management, logistics, or business administration." ,
    },
    {
      "image" : "https://www.freepnglogos.com/uploads/amazon-png-logo-vector/online-pig-weight-calculator-amazon-png-logo-vector-23.png",
      "title" : "Python Developer",
      "details" : "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia, molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum numquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium optio, eaque rerum! Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut! Impedit sit sunt quaerat, odit, tenetur error, harum nesciunt ipsum debitis quas aliquid. Reprehenderit, quia. Quo neque error repudiandae fuga? Ipsa laudantium molestias eos sapiente officiis modi at sunt excepturi.",
      "salary" : "\$12,00,0000/yr",
      "company" : "Amazon",
      "type" : "Full–time",
      "location" : "India, Delli.",
      "vacancy" : "7",
      "edu" : "BSC in CSE." ,
    },
    {
      "image" : "https://www.iprcenter.gov/image-repository/alibaba_logo.png/@@images/image.png",
      "title" : "Java Developer",
      "details" : "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia, molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum numquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium optio, eaque rerum! Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut! Impedit sit sunt quaerat, odit, tenetur error, harum nesciunt ipsum debitis quas aliquid. Reprehenderit, quia. Quo neque error repudiandae fuga? Ipsa laudantium molestias eos sapiente officiis modi at sunt excepturi.",
      "salary" : "\$9,00,0000/yr",
      "company" : "Alibaba",
      "type" : "Full–time",
      "location" : "India, Delli.",
      "vacancy" : "10",
      "edu" : "BSC in CSE." ,
    },
    {
      "image" : "https://www.iprcenter.gov/image-repository/alibaba_logo.png/@@images/image.png",
      "title" : "Java Developer",
      "details" : "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia, molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum numquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium optio, eaque rerum! Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut! Impedit sit sunt quaerat, odit, tenetur error, harum nesciunt ipsum debitis quas aliquid. Reprehenderit, quia. Quo neque error repudiandae fuga? Ipsa laudantium molestias eos sapiente officiis modi at sunt excepturi.",
      "salary" : "\$9,00,0000/yr",
      "type" : "Full–time",
      "company" : "Google",
      "location" : "India, Delli.",
      "vacancy" : "10",
      "edu" : "BSC in CSE." ,
    },
    {
      "image" : "https://img.freepik.com/free-icon/search_318-265146.jpg",
      "title" : "Senior Software Developer",
      "details" : "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia, molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum numquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium optio, eaque rerum! Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut! Impedit sit sunt quaerat, odit, tenetur error, harum nesciunt ipsum debitis quas aliquid. Reprehenderit, quia. Quo neque error repudiandae fuga? Ipsa laudantium molestias eos sapiente officiis modi at sunt excepturi.",
      "salary" : "\$1,00,0000/yr",
      "company" : "Google",
      "type" : "Full–time",
      "location" : "Anywhere in India",
      "vacancy" : "3",
      "edu" : "Bachelor's degree in supply chain management, logistics, or business administration." ,
    },
    {
      "image" : "https://www.freepnglogos.com/uploads/amazon-png-logo-vector/online-pig-weight-calculator-amazon-png-logo-vector-23.png",
      "title" : "Python Developer",
      "details" : "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia, molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum numquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium optio, eaque rerum! Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut! Impedit sit sunt quaerat, odit, tenetur error, harum nesciunt ipsum debitis quas aliquid. Reprehenderit, quia. Quo neque error repudiandae fuga? Ipsa laudantium molestias eos sapiente officiis modi at sunt excepturi.",
      "salary" : "\$12,00,0000/yr",
      "company" : "Amazon",
      "type" : "Full–time",
      "location" : "India, Delli.",
      "vacancy" : "7",
      "edu" : "BSC in CSE." ,
    },
    {
      "image" : "https://www.iprcenter.gov/image-repository/alibaba_logo.png/@@images/image.png",
      "title" : "Java Developer",
      "details" : "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia, molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum numquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium optio, eaque rerum! Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut! Impedit sit sunt quaerat, odit, tenetur error, harum nesciunt ipsum debitis quas aliquid. Reprehenderit, quia. Quo neque error repudiandae fuga? Ipsa laudantium molestias eos sapiente officiis modi at sunt excepturi.",
      "salary" : "\$9,00,0000/yr",
      "company" : "Alibaba",
      "type" : "Full–time",
      "location" : "India, Delli.",
      "vacancy" : "10",
      "edu" : "BSC in CSE." ,
    },
    {
      "image" : "https://www.iprcenter.gov/image-repository/alibaba_logo.png/@@images/image.png",
      "title" : "Java Developer",
      "details" : "Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime mollitia, molestiae quas vel sint commodi repudiandae consequuntur voluptatum laborum numquam blanditiis harum quisquam eius sed odit fugiat iusto fuga praesentium optio, eaque rerum! Provident similique accusantium nemo autem. Veritatis obcaecati tenetur iure eius earum ut molestias architecto voluptate aliquam nihil, eveniet aliquid culpa officia aut! Impedit sit sunt quaerat, odit, tenetur error, harum nesciunt ipsum debitis quas aliquid. Reprehenderit, quia. Quo neque error repudiandae fuga? Ipsa laudantium molestias eos sapiente officiis modi at sunt excepturi.",
      "salary" : "\$9,00,0000/yr",
      "type" : "Full–time",
      "company" : "Google",
      "location" : "India, Delli.",
      "vacancy" : "10",
      "edu" : "BSC in CSE." ,
    }
  ];
}